<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-26T01:09:16 IST" name="Suite" finished-at="2023-08-26T01:10:36 IST" duration-ms="80097">
    <groups>
    </groups>
    <test started-at="2023-08-26T01:09:16 IST" name="Test" finished-at="2023-08-26T01:10:36 IST" duration-ms="80097">
      <class name="com.itlearn.testcases.LoginTestDriverData">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.itlearn.testcases.LoginTestDriverData@53045c6c]" started-at="2023-08-26T01:09:16 IST" name="setUp" finished-at="2023-08-26T01:10:21 IST" duration-ms="65336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLogin(java.lang.String,java.lang.String)[pri:1, instance:com.itlearn.testcases.LoginTestDriverData@53045c6c]" started-at="2023-08-26T01:10:23 IST" name="verifyLogin" data-provider="LoginDataProvider" finished-at="2023-08-26T01:10:32 IST" duration-ms="9504" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Demo12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123456$]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method signature="verifyLogin(java.lang.String,java.lang.String)[pri:1, instance:com.itlearn.testcases.LoginTestDriverData@53045c6c]" started-at="2023-08-26T01:10:32 IST" name="verifyLogin" data-provider="LoginDataProvider" finished-at="2023-08-26T01:10:35 IST" duration-ms="2961" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Demo12343465]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123456$]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.itlearn.testcases.LoginTestDriverData.verifyLogin(LoginTestDriverData.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.itlearn.testcases.LoginTestDriverData@53045c6c]" started-at="2023-08-26T01:10:35 IST" name="tearDown" finished-at="2023-08-26T01:10:36 IST" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.itlearn.testcases.LoginTestDriverData -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
